post_create:
  path: 'create'
  methods: [ PUT ]
  defaults: { _controller: PostBundle:Post:create }

post_update:
  path: '{id}/update'
  methods: [ POST ]
  defaults: { _controller: PostBundle:Post:update }

post_get:
  path: '{id}/get'
  methods: [ GET ]
  defaults: {_controller: PostBundle:Post:get }

post_delete:
  path: '{id}/delete'
  methods: [ DELETE ]
  defaults: { _controller: PostBundle:Post:delete }
