change_password:
  path:     /change-password
  defaults:
   _controller: AuthBundle:ChangePassword:changePassword
  methods: [ POST ]



confirm_mail_send_code:
  path: /send-confirm
  defaults:
    _controller: AuthBundle:SendMail:sendMail
  methods: [ POST ]

confirm_mail_by_code:
  path: /confirm-mail/{code}
  defaults:
    _controller: AuthBundle:SendMail:confirmEmailByCode
  methods: [ GET ]